#!/bin/python3

#Given a string containing just the characters '(', ')', '{', '}', '[' and ']', 
# determine if the input string is valid.


class Solution:
	def isValid(self, s):
		"""
        :type s: str
        :rtype: bool
		"""
		parens = {'{':'}','(':')', '[':']'}
	
		#Push opening braces to stack, closing brace can be matched

		stack = list()

		for c in s:
			if c in parens:
				stack.append(c)
			elif len(stack)==0 or c != parens[stack.pop()]:
				return False

		if len(stack)>0:
			return False

		return True		
	
def main():

	print ("valid parenthesis")
	sol = Solution()
	
	target = "{{[]}}"
	#target = "{{{{"
	result = sol.isValid(target)

	print(result)

if __name__=="__main__":main()
