#!/bin/python3

import collections
#Leetcode 404, Find the sum of all left leaves (only leaves not nodes) in a given binary tree.

class Solution(object):

	def sumOfLeftLeaves(self, root):
		
		if not root:
			return 0
			
		sum_=0
		if root.left and not root.left.left and not root.left.right:
        		sum_ = root.left.val
		
		sum_ += self.sumOfLeftLeaves(root.left) + self.sumOfLeftLeaves(root.right)
			
		return sum_
		
class TreeNode:

	def __init__(self, val, left=None, right=None):
		self.val = val
		self.left = left
		self.right = right					
def main():

	
	l7 = TreeNode(7, TreeNode(10), TreeNode(11))
	l15 = TreeNode(15, TreeNode(2), TreeNode(20))	
	#l7 = TreeNode(7)
	#l15 = TreeNode(15)	
	l9 = TreeNode(9)
	l20 = TreeNode(20, l15,l7)	
	l3 = TreeNode(3, l9,l20)
	
	
	sol = Solution()
	sumLeft = sol.sumOfLeftLeaves(l3)
	print("SUM", sumLeft)
	
if __name__=="__main__":main()
