#!/bin/python3

import collections
# Write a program that outputs the string representation of numbers from 1 to n.
# for multiples of three it should output \u201cFizz\u201d instead of the number 
# and for the multiples of five output \u201cBuzz\u201d. 
# For numbers which are multiples of both three and five output \u201cFizzBuzz\u201d.

class Solution(object):

	def fizzBuzz(self, n):
		"""
		:type n: int
		:rtype: List[str]
		"""
		r_list = []
		
		for i in range(1, n+1):
		
			if i%3==0 and i%5==0:
				r_list.append("FizzBuzz")
			elif i%3==0:
				r_list.append("Fizz")
			elif i%5==0:
				r_list.append("Buzz")
			else:
				r_list.append(str(i))				
		
		return r_list
					
def main():
	sol = Solution()
	
	result = sol.fizzBuzz(15)
	print(result)
	
if __name__=="__main__":main()
